### ISSUE TITLE
Can't call `torch.tensor` within grad

### ISSUE THREAD

**Issue by Chillee** [facebookresearch/functorch#7]
```
from functorch import grad, vmap
import torch

def f(x):
    t = torch.tensor(0)
    return t + x
inps = (torch.randn([]),)
print(grad(f)(*inps))
```

```
Traceback (most recent call last):
  File "t.py", line 8, in <module>
    print(grad(f)(*inps))
  File "/home/chilli/fb/functorch/functorch/_src/eager_transforms.py", line 152, in wrapper
    results = grad_and_value(f, argnums, has_aux=has_aux)(*args)
  File "/home/chilli/fb/functorch/functorch/_src/eager_transforms.py", line 110, in wrapper
    output = f(*args)
  File "t.py", line 5, in f
    t = torch.tensor(0)
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
```

**Comment by zou3519** [comment]
https://github.com/zou3519/functorch/issues/14 is a pretty fun test case. One of my previous proposed solutions, "whenever you call empty, don't return a TensorWrapper; return a TensorWrapper for all other operations" doesn't actually work. The problem is that if the user calls empty and then does a .copy_(), we really wanted the tensor returned from empty to have a TensorWrapper because the .copy_() is going to assign history to it.

**Comment by zou3519** [comment]
I think we're going to need an extension point in core for this. For the other solution we discussed (just attaching the storage to TensorWrapper) I'm worried about aliasing because this would effectively make TensorWrapper a view on another Tensor.

**Comment by ezyang** [comment]
One of the problems with `torch.tensor` is we're reading in the data from a legitimately arbitrarily Python object, so there isn't really any way to get things to work without mutating a tensor first. What it seems like you want to happen in this case is for a normal, non mode overridden tensor to get constructed, you mutate into it, and THEN you alias it into the wrapper.

**Comment by zou3519** [comment]
>  What it seems like you want to happen in this case is for a normal, non mode overridden tensor to get constructed, you mutate into it, and THEN you alias it into the wrapper.

Here are two possible options:

## Option 1: Easy fix

To achieve this it looks like we can just put ` c10::impl::ExcludeDispatchKeyGuard dynamic_layer_back_guard(c10::DispatchKey::FuncTorchDynamicLayerBackMode);`  [here](https://github.com/pytorch/pytorch/blob/7f6b2bc2d01cb94cbd24b563479a365d13b100e9/torch/csrc/utils/tensor_new.cpp#L260-L261)

The FuncTorchDynamicLayerBackMode key's fallback is responsible for re-wrapping tensors and we want to make it so that the normal tensor gets constructed, we mutate into it, and then aliasing in the wrapper happens in the call to `.to(...)` ([here](https://github.com/pytorch/pytorch/blob/7f6b2bc2d01cb94cbd24b563479a365d13b100e9/torch/csrc/utils/tensor_new.cpp#L278)) because `.to` will dispatch to  FuncTorchDynamicLayerBackMode

## Option 2: Add an extension point for `internal_new_from_data`

We introduce some operator that does `internal_new_from_data` (https://github.com/pytorch/pytorch/blob/7f6b2bc2d01cb94cbd24b563479a365d13b100e9/torch/csrc/utils/tensor_new.cpp#L201).

A glaring problem is that native_functions codegen doesn't support PyObject* data. But this solution would be more general.
We don't have a particular use case for this generic solution yet, so I'm inclined to go with Option 1 for now

**Comment by zou3519** [comment]
Re-opening this because the hack I applied was very non-kosher and is getting reverted
